apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-postgres
  namespace: gluon-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-postgres
  template:
    metadata:
      labels:
        app: payment-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "payment"
            - name: POSTGRES_USER
              value: "payment"
            - name: POSTGRES_PASSWORD
              value: "payment"
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "payment"]
            initialDelaySeconds: 2
            periodSeconds: 2
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: payment-postgres
  namespace: gluon-local
spec:
  selector:
    app: payment-postgres
  ports:
    - port: 5432
      targetPort: 5432
