apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-redis
  namespace: gluon-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-redis
  template:
    metadata:
      labels:
        app: catalog-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 2
            periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-redis
  namespace: gluon-local
spec:
  selector:
    app: catalog-redis
  ports:
    - port: 6379
      targetPort: 6379
